version: "3"
services:
  postgres-db:
    image: "postgres"
    container_name: "node-gmp-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"
